_target_: src.model.layout_transformer.LayoutTransformer
_partial_: true
# vocab_size: ???
# block_size: ???
n_layer: 24
n_head: 16
n_embd: 1024
embd_pdrop: 0.1
resid_pdrop: 0.1
attn_pdrop: 0.1
pe_mode: "param"