_target_: src.model.layout_transformer.LayoutTransformer
_partial_: true
# vocab_size: ???
# block_size: ???
n_layer: 6
n_head: 8
n_embd: 512
embd_pdrop: 0.1
resid_pdrop: 0.1
attn_pdrop: 0.1
pe_mode: "param"